version: '3.8'
# name: "vide-grenier-en-ligne"
services:
  web:
      container_name: app-container
      build: .
      ports:
        - "8080:80"
      # volumes:
      #   - ../../:/var/www/html/
      networks:
        - vgelnetwork
      depends_on:
        - db
  db:
      container_name: db-container
      image: mysql:8.0
      environment:
        MYSQL_ROOT_PASSWORD: 653rag9T
        MYSQL_DATABASE: videgrenierenligne
        MYSQL_USER: webapplication
        MYSQL_PASSWORD: 653rag9T
      ports:
        - "3306:3306"
      volumes:
        - ./sql/import.sql:/docker-entrypoint-initdb.d/data.sql
      networks:
        vgelnetwork:
          ipv4_address: 172.20.0.5
networks:
  vgelnetwork:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
volumes:
  persistent: