name: Deploy

on:
    repository_dispatch:
        types: [deploy]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            # - name: Download Docker image artifacts
            #   uses: actions/download-artifact@v2
            #   with:
            #     name: docker-images
            #     path: docker-images

            # - name: Load Docker images
            #   run: |
            #     docker load -i docker-images/demo_web.tar
            #     docker load -i docker-images/demo_db.tar

            - name: Deploy to server
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.RPI_HOST }}
                username: ${{ secrets.RPI_USERNAME }}
                key: ${{ secrets.RPI_KEY }}
                port: ${{ secrets.RPI_PORT }}
                script: |
                  # docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
                  # Execute the script on the remote server
                  /home/lbantoine/code/c5-grenier/docker/prod/deploy.sh