name: ci-feature-dev
on: 
  push:
    branches:
      - 'feature/ci-integration'
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Setup Build Image
      #   run: docker-compose -f docker/demo/docker-compose.ci.yml build --no-cache && docker-compose up -d

      - name: Run Build Image
        run: docker-compose -f docker/demo/docker-compose.ci.yml up -d --wait

      - name: Wait for service to become available
        run: sleep 10s

      - name: Get available containers
        run: docker ps -a

      - name: Logs for app
        run: docker logs app-container

      - name: Logs for db
        run: docker logs db-container

      - name: Run a curl test on app
        run: curl http://localhost:8080/